GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Aeneid",
    "author": "Virgilio",
    "url": "http://fakelink3",
    "likes": 2000
}