POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mlenders",
    "password": "testpass",
    "name": "Mark Lenders"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "cfaenza",
    "password": "passwordprova"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mlenders",
    "password": "testpass"
}
